import { DealType } from "@/app/lib/definitions";

const deals: DealType[] = [
  {
    id: "1",
    name: "Soultrain",
    totalCommitment: "$300,000,000.00",
    funded: "$100,000,000.00",
    unfunded: "$200,000,000.00",
    lender: {
      covenantsTracking: [
        {
          title: "Quick Ratio",
          value: 6.68,
          change: "-12.5%",
          changeValue: "7.63",
          status: "Passed",
          prevPeriodValue: "Min 5.00",
        },
        {
          title: "Debt-to-EBITDA",
          value: 2.51,
          change: "+10.2%",
          changeValue: "2.27",
          status: "Failed",
          prevPeriodValue: "Max 2.50",
        },
        {
          title: "Fixed Charge Coverage Ratio",
          value: 1.56,
          change: "-3.00%",
          changeValue: "1.61",
          status: "Passed",
          prevPeriodValue: "Min 1.20",
        },
      ],
      upcomingPayments: {
        credits: [
          {
            id: "credit-1",
            dueDate: "2025-01-18",
            status: "5 days overdue",
            drawDownFee: "$100,000.00",
            total: "$100,000.00",
          },
          {
            id: "credit-2",
            dueDate: "2025-02-03",
            status: "in 10 days",
            interest: "$849,315.07",
            total: "$849,315.07",
            noticeId: "notice-1",
          },
        ],
        debits: [
          {
            id: "debit-1",
            dueDate: "2025-01-24",
            status: "Pending",
            drawDownFee: "$5,000.00",
            drawDown: "$5,000,000.00",
            total: "$4,955,000.00",
            transactionId: "transaction-1",
          },
        ],
      },
      positions: [
        {
          id: "position-1",
          deal: "Soultrain",
          instrument: "New Fixed Loan",
          borrower: "Soultrain",
          ccy: "USD",
          counterparty: "Funky Fund East",
          role: "LENDER",
          committed: "$100,000,000.00",
          funded: "$100,000,000.00",
          unfunded: "$0.0",
          docs: "",
        },
      ],
      transactions: [
        {
          id: "transaction-1",
          paymentType: "Credit",
          type: "Drawdown",
          deal: "Soultrain",
          instrument: "Soultrain Revolver",
          borrower: "Soultrain",
          ccy: "USD",
          counterparty: "Soultrain Music Awards",
          paymentDate: "2024-01-24",
          amount: "$5,000,000.00",
          role: "LENDER 2",
          committed: "$200,000,000.00",
          funded: "$0.0",
          unfunded: "$200,000,000.00",
          status: "Pending",
          rateInfo: {
            type: "Fixed",
            dayCount: "ACT/360",
            accrualStartDate: "2025-01-24",
            accrualEndDate: "2025-02-24",
          },
          interestAmount: {
            date: "2025-01-24",
            rate: "8.5600",
            principal: "$5,000,000.00",
            amount: "$36,855.56",
          },
          allocations: [
            {
              role: "Borrower",
              counterparty: "Soul Train Music Awards",
              amount: "(849,315.07)", // Negative values are shown in parentheses
              share: "(100.00%)",
            },
            {
              role: "Lender",
              counterparty: "Funky Fund East",
              amount: "849,315.07", // Positive value
              share: "100.00%",
            },
          ],
        },
      ],
      asOfDate: "2025-01-24",
      documents: [
        {
          id: "document-1",
          documentName: "Soultrain Drawdown",
          documentType: "Transaction",
          documentSubType: "Other",
          deal: "Soultrain",
          transaction: "Drawdown",
          transactionDate: "2024-01-01",
          amount: "$1,000,000.00",
          documentDate: "2024-10-30",
          fileType: "PDF",
          status: "Open",
        },
      ],
    },
    borrower: {
      covenantsTracking: [
        {
          title: "Quick Ratio",
          value: 6.68,
          change: "-12.5%",
          changeValue: "7.63",
          status: "Passed",
          prevPeriodValue: "Min 5.00",
        },
        {
          title: "Debt-to-EBITDA",
          value: 2.51,
          change: "+10.2%",
          changeValue: "2.27",
          status: "Failed",
          prevPeriodValue: "Max 2.50",
        },
        {
          title: "Fixed Charge Coverage Ratio",
          value: 1.56,
          change: "-3.00%",
          changeValue: "1.61",
          status: "Passed",
          prevPeriodValue: "Min 1.20",
        },
      ],
      upcomingPayments: {
        credits: [
          {
            id: "credit-1",
            dueDate: "2025-01-18",
            status: "Pending",
            drawDown: "$5,000,000.00",
            drawDownFee: "$5,000.00",
            total: "$4,955,000.00",
          },
        ],
        debits: [
          {
            id: "debit-1",
            dueDate: "2025-01-18",
            status: "5 days overdue",
            drawDownFee: "$100,000.00",
            total: "$100,000.00",
          },
          {
            id: "debit-2",
            dueDate: "2025-02-03",
            status: "in 10 days",
            interest: "$849,315.07",
            total: "$849,315.07",
          },
        ],
      },
      positions: [
        {
          id: "position-1",
          deal: "Soultrain",
          instrument: "New Fixed Loan",
          borrower: "Soultrain",
          ccy: "USD",
          counterparty: "Funky Fund East",
          role: "LENDER",
          committed: "$100,000,000.00",
          funded: "$100,000,000.00",
          unfunded: "$0.0",
          docs: "",
        },
      ],
      transactions: [],
      asOfDate: "2024-02-04",
    },
  },
  {
    id: "2",
    name: "abcCapital",
    totalCommitment: "$2,500,000",
    funded: "$680,000",
    unfunded: "$1,820,000",
    lender: {
      covenantsTracking: [
        {
          title: "Quick Ratio",
          value: 6.68,
          change: "-12.5%",
          changeValue: "7.63",
          status: "Passed",
          prevPeriodValue: "Min 5.00",
        },
        {
          title: "Debt-to-EBITDA",
          value: 2.51,
          change: "+10.2%",
          changeValue: "2.27",
          status: "Failed",
          prevPeriodValue: "Max 2.50",
        },
        {
          title: "Fixed Charge Coverage Ratio",
          value: 1.56,
          change: "-3.00%",
          changeValue: "1.61",
          status: "Passed",
          prevPeriodValue: "Min 1.20",
        },
      ],
      upcomingPayments: {
        credits: [
          {
            id: "credit-1",
            dueDate: "2025-01-18",
            status: "5 days overdue",
            drawDownFee: "$100,000.00",
            total: "$100,000.00",
          },
          {
            id: "credit-2",
            dueDate: "2025-02-03",
            status: "in 10 days",
            interest: "$849,315.07",
            total: "$849,315.07",
            noticeId: "notice-1",
          },
        ],
        debits: [
          {
            id: "debit-1",
            dueDate: "2025-01-24",
            status: "Pending",
            drawDownFee: "$5,000.00",
            drawDown: "$5,000,000.00",
            total: "$4,955,000.00",
            transactionId: "transaction-1",
          },
        ],
      },
      positions: [
        {
          id: "position-5",
          deal: "ABC Capital",
          instrument: "Capital Loan",
          borrower: "ABC Corp",
          ccy: "USD",
          counterparty: "Michael",
          role: "LENDER",
          committed: "$150,000,000.00",
          funded: "$0.0",
          unfunded: "$150,000,000.00",
          docs: "$0.0",
        },
        {
          id: "position-7",
          deal: "ABC Capital",
          instrument: "Capital Loan",
          borrower: "ABC Corp",
          ccy: "USD",
          counterparty: "Michael",
          role: "LENDER",
          committed: "$180,000,000.00",
          funded: "$0.0",
          unfunded: "$180,000,000.00",
          docs: "$0.0",
        },
      ],
      transactions: [],
      asOfDate: "2024-02-04",
    },
    borrower: {
      covenantsTracking: [
        {
          title: "Quick Ratio",
          value: 6.68,
          change: "-12.5%",
          changeValue: "7.63",
          status: "Passed",
          prevPeriodValue: "Min 5.00",
        },
        {
          title: "Debt-to-EBITDA",
          value: 2.51,
          change: "+10.2%",
          changeValue: "2.27",
          status: "Failed",
          prevPeriodValue: "Max 2.50",
        },
        {
          title: "Fixed Charge Coverage Ratio",
          value: 1.56,
          change: "-3.00%",
          changeValue: "1.61",
          status: "Passed",
          prevPeriodValue: "Min 1.20",
        },
      ],
      upcomingPayments: {
        credits: [
          {
            id: "credit-1",
            dueDate: "2025-01-18",
            status: "5 days overdue",
            drawDownFee: "$100,000.00",
            total: "$100,000.00",
          },
        ],
        debits: [
          {
            id: "debit-1",
            dueDate: "2025-01-18",
            status: "5 days overdue",
            prepaymentFee: "$1,601,94",
            total: "$1,601,94",
          },
          {
            id: "debit-2",
            dueDate: "2025-02-03",
            status: "in 10 days",
            interest: "$56,978.00",
            principalRepayment: "$50,000.00",
            total: "$56,978.00",
          },
        ],
      },
      positions: [
        {
          id: "position-6",
          deal: "ABC Capital",
          instrument: "Capital Loan",
          borrower: "ABC Corp",
          ccy: "USD",
          counterparty: "Michael",
          role: "LENDER",
          committed: "$180,000,000.00",
          funded: "$0.0",
          unfunded: "$180,000,000.00",
          docs: "$0.0",
        },
        {
          id: "position-8",
          deal: "ABC Capital",
          instrument: "Capital Loan",
          borrower: "ABC Corp",
          ccy: "USD",
          counterparty: "Michael",
          role: "LENDER",
          committed: "$190,000,000.00",
          funded: "$0.0",
          unfunded: "$190,000,000.00",
          docs: "$0.0",
        },
      ],
      transactions: [],
      asOfDate: "2024-02-04",
    },
  },
];

const formTableData = {
  name: "New Fixed Loan",
  loanType: "Term Loan",
  loanAmount: "100,000,000.00",
  ccy: "USD",
  issueDate: "2025-01-01",
  maturityDate: "2030-01-01",
  deal: "Soultrain Deal",
  borrower: "Soultrain Music Awards",
  lender: "Funky Fund East",
  lenderShare: "100,000,000.00",
  rateType: "Fixed",
  annualRate: "10.00%",
  paid: "Monthly",
  dayCount: "ACT/365",
};

const formTableDataAdvanced = {
  name: "New Fixed Loan",
  loanType: "Term Loan",
  loanAmount: "100,000,000.00",
  ccy: "USD",
  issueDate: "2025-01-01",
  maturityDate: "2030-01-01",
  deal: "Soultrain Deal",
  borrower: "Soultrain Music Awards",
  lender: "Funky Fund East",
  lenderShare: "100,000,000.00",
  rateType: "Fixed",
  annualRate: "10.00%",
  paid: "Monthly",
  businessDayCalendars: "New York, London",
  nonBusinessDayRule: "Modified Next Business Day",
  dayCount: "ACT/365",
  pikOption: "Cash or PIK",
  pikReducesUnfunded: "No",
  rateScale: 4,
  includeAccrualEnd: true,
  accrualEndAdj: true,
  spreads: [
    {
      date: "2025-01-01",
      spreadType: "Standard",
      spread: "10.0000%",
      spreadAdj: "+0.1000%",
    },
    {
      date: "2026-01-01",
      spreadType: "Standard",
      spread: "12.0000%",
      spreadAdj: "+0.1000%",
    },
    {
      date: "2025-01-01",
      spreadType: "PIK",
      spread: "20.0000%",
      spreadAdj: "+0.5000%",
    },
    {
      date: "2026-01-01",
      spreadType: "PIK",
      spread: "22.0000%",
      spreadAdj: "+0.5000%",
    },
    {
      date: "2025-01-01",
      spreadType: "Standard Participation",
      spread: "8.0000%",
      spreadAdj: "-",
    },
  ],
  facilityFees: [
    {
      type: "Upfront Fee",
      appliesTo: "N/A",
      rate: "-",
      flatAmount: "$1,500.00",
    },
    {
      type: "Unfunded Fee",
      appliesTo: "Current Unfunded",
      rate: "1.5000%",
      flatAmount: "-",
    },
    {
      type: "Prepayment Fee",
      appliesTo: "Prepayment Amount",
      rate: "0.5000%",
      flatAmount: "-",
    },
    {
      type: "Drawdown Fee",
      appliesTo: "Drawdown Amount",
      rate: "0.1000%",
      flatAmount: "-",
    },
    {
      type: "Commitment Fee",
      appliesTo: "Commitment Amount",
      rate: "0.1000%",
      flatAmount: "-",
    },
    {
      type: "Administrative Fee",
      appliesTo: "N/A",
      rate: "-",
      flatAmount: "$1,500.00",
    },
  ],
  accrualFrequency: 1,
  accrualFrequencyUnit: "Month End",
  adjustmentValue: 1,
  adjustmentType: "Business Day of the Month",
};

const transactionsTableData = [
  {
    transaction: "Commitment",
    date: "2025-01-01",
    amount: "$100,000,000.00",
  },
  {
    transaction: "Drawdown",
    date: "2025-01-01",
    amount: "$100,000,000.00",
  },
  {
    transaction: "Interest Payment",
    date: "2025-02-01",
    amount: "$849,315.07",
  },
  {
    transaction: "Interest Payment",
    date: "2025-03-01",
    amount: "$767,123.29",
  },
  {
    transaction: "Interest Payment",
    date: "2025-04-01",
    amount: "$849,315.07",
  },
  {
    transaction: "Interest Payment",
    date: "2025-05-01",
    amount: "$821,917.81",
  },
  {
    transaction: "Interest Payment",
    date: "2025-06-01",
    amount: "$849,315.07",
  },
  {
    transaction: "Interest Payment",
    date: "2025-07-01",
    amount: "$821,917.81",
  },
  {
    transaction: "Interest Payment",
    date: "2025-08-01",
    amount: "$849,315.07",
  },
  {
    transaction: "Interest Payment",
    date: "2025-09-01",
    amount: "$849,315.07",
  },
  {
    transaction: "Interest Payment",
    date: "2025-10-01",
    amount: "$821,917.81",
  },
  {
    transaction: "Interest Payment",
    date: "2025-11-01",
    amount: "$849,315.07",
  },
  {
    transaction: "Interest Payment",
    date: "2025-12-01",
    amount: "$821,917.81",
  },
  {
    transaction: "Interest Payment",
    date: "2026-01-01",
    amount: "$849,315.07",
  },
  {
    transaction: "Interest Payment",
    date: "2026-02-01",
    amount: "$849,315.07",
  },
  {
    transaction: "Interest Payment",
    date: "2026-03-01",
    amount: "$767,123.29",
  },
  {
    transaction: "Interest Payment",
    date: "2026-04-01",
    amount: "$849,315.07",
  },
  {
    transaction: "Interest Payment",
    date: "2026-05-01",
    amount: "$821,917.81",
  },
];

export { deals, formTableData, transactionsTableData, formTableDataAdvanced };
